import type { NextPage } from 'next'
import { signIn, signOut, useSession } from 'next-auth/react'
import Head from 'next/head'
import Link from 'next/link'

const Home: NextPage = () => {
  const { data: session } = useSession()
  return (
    <div>
      <Head>
        <title>Blog App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="p-5 flex flex-col space-y-4">
        <div>Hello World</div>
        {!session ? (
          <button
            onClick={() => {
              signIn('google', { callbackUrl: '/' })
            }}
            className="py-2 px-4 rounded-md bg-purple-700 text-purple-100 text-sm"
          >
            Sign In
          </button>
        ) : (
          <button
            onClick={() => {
              signOut({ callbackUrl: '/' })
            }}
            className="py-2 px-4 rounded-md bg-purple-700 text-purple-100 text-sm"
          >
            Sign Out
          </button>
        )}
      </div>
    </div>
  )
}

export default Home
